### ISSUE TITLE
3D head ?size is not working.

### ISSUE THREAD

**Issue by FrozenBeard** [crafatar/setup#5]
The flat head ?size parameter is working, its not on 3D heads, see example:
https://crafatar.com/renders/head/101f87d4-7051-4e34-897f-89f8acc4a36c?size=4

**Comment by jomo** [comment]
[Renders](https://crafatar.com/#head-renders) use the `scale` paramter instead of `size`.
We chose different names because `size` is the actual width/height in pixels and `scale` behaves a bit different.

**Comment by jomo** [comment]
PS: Didn't notice before, but this repo is used for setting up crafatar.
Please use the [crafatar](https://github.com/crafatar/crafatar) repo for issues with Crafatar itself :)

**Comment by FrozenBeard** [comment]
That makes sense, you should make that more clear on your homepage that the 3D head requires scale when you click the modifiers link under it :)
awesome.

**Comment by jomo** [comment]
Please have a look at https://github.com/crafatar/crafatar/commit/4302a95f6c040a4236247eb4099b187c6b12e692, is that better?
